stages:
  - main-build
  - additional-build

variables:
  GIT_DEPTH: "1"
  CONTAINER_REGISTRIES: |
    voxsoft/kube-helm-multitool
    voxmaster/kube-helm-multitool
    $CI_REGISTRY_IMAGE
  HELM_MAJOR_VERSION: "v3"

default:
  image: ezkrg/buildx:latest
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    ## Get current cli versions if not predefined
    - apk add curl
    ## kubernetes-cli
    - if [ -z ${K8S_VERSION+x} ];
        then export K8S_VERSION=$(curl -Ls https://github.com/kubernetes/kubernetes/tags | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz' | head -n 1 | cut -d '.' -f -3);
        else echo "Kubernetes-cli version forced to '$K8S_VERSION'";
      fi
    - export K8S_VERSION_MINOR=$(echo ${K8S_VERSION} | cut -d '.' -f -2)
    ## helm
    - if [ -z ${HELM_VERSION+x} ];
        then export HELM_VERSION=$(curl -Ls https://github.com/helm/helm/tags | grep -oE "${HELM_MAJOR_VERSION}\.[0-9]+\.[0-9]+\.tar\.gz" | head -n 1 | cut -d '.' -f -3);
        else echo "Helm version forced to '$HELM_VERSION'";
      fi
    - export HELM_VERSION_MINOR=$(echo ${HELM_VERSION} | cut -d '.' -f -2)
    ## google cloud sdk
    - if [ -z ${CLOUD_SDK_VERSION+x} ];
        then export CLOUD_SDK_VERSION=$(curl -Ls https://github.com/GoogleCloudPlatform/cloud-sdk-docker/tags | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz' | head -n 1 | cut -d '.' -f -3);
        else echo "Google Cloud SDK version forced to '$CLOUD_SDK_VERSION'";
      fi
    ## Show versions in job log:
    - echo -e "
      \n kubectl:\e[44m ${K8S_VERSION} \e[0m 
      \n helm:\e[44m ${HELM_VERSION} \e[0m 
      \n gcloud:\e[44m ${CLOUD_SDK_VERSION} \e[0m"
    ## Create release image tag
    - export RELEASE=${K8S_VERSION}-${HELM_VERSION}
    - export RELEASE_MINOR=${K8S_VERSION_MINOR}-${HELM_VERSION_MINOR}
    - export RELEASE_MINOR_HELM_MAJOR=${K8S_VERSION_MINOR}-${HELM_MAJOR_VERSION}
    ## Enable experimental feature to be able to inspect remote images
    - 'mkdir -p ~/.docker && echo ''{"experimental": "enabled"}'' > ~/.docker/config.json'
    ## Authenticate to Container Registry
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASSWORD

Build Main Image:
  stage: main-build
  script:
    ## Stop if image already exists
    - if [ "${FORCE_REBUILD}" == "true" ];
        then echo -e "\e[41mImage Rebuild Forced!\e[0m";
        else docker manifest inspect ${CI_REGISTRY_IMAGE}:${RELEASE} > /dev/null && echo -e "\e[44mVersion ${RELEASE} is already exists\e[0m" && exit 0;
      fi
    - if echo "$HELM_VERSION" | grep '^v2' >/dev/null ; then echo -e "\e[104m.But for v2. Exiting\e[0m" && exit 0; fi
    # Create a set of tags for the image with multiple registries
    - for REGISTRY in $CONTAINER_REGISTRIES; do
        TAGS="$TAGS -t ${REGISTRY}:${RELEASE} -t ${REGISTRY}:${RELEASE_MINOR} -t ${REGISTRY}:${RELEASE_MINOR_HELM_MAJOR} -t ${REGISTRY}:latest" ;
      done
    ## Build and push container images
    - docker buildx create --name mybuilder --use
    - docker buildx build --platform linux/arm64/v8,linux/amd64 --push
        $TAGS
        --build-arg K8S_VERSION=${K8S_VERSION}
        --build-arg HELM_VERSION=${HELM_VERSION} .
  only:
    - master
    - develop

.Build Additional Image:
  stage: additional-build
  script:
    ## Stop if image already exists
    - if [ "${FORCE_REBUILD}" == "true" ];
        then echo -e "\e[41mImage Rebuild Forced!\e[0m";
        else docker manifest inspect ${CI_REGISTRY_IMAGE}:${RELEASE}-${ADDITION} > /dev/null && echo -e "\e[44mVersion ${RELEASE}-${ADDITION} is already exists\e[0m" && exit 0;
      fi
    # Create a set of tags for the image with multiple registries
    - for REGISTRY in $CONTAINER_REGISTRIES; do
        TAGS="$TAGS -t ${REGISTRY}:${RELEASE}-${ADDITION} -t ${REGISTRY}:${RELEASE_MINOR}-${ADDITION} -t ${REGISTRY}:${RELEASE_MINOR_HELM_MAJOR}-${ADDITION} -t ${REGISTRY}:${ADDITION}" ;
      done
    ## Build container image
    - docker buildx create --name mybuilder --use
    - docker buildx build --platform linux/arm64/v8,linux/amd64 --push
        $TAGS
        --build-arg K8S_VERSION=${K8S_VERSION}
        --build-arg HELM_VERSION=${HELM_VERSION} 
        --build-arg CLOUD_SDK_VERSION=${CLOUD_SDK_VERSION} 
        -f ${ADDITION}.Dockerfile .
  only:
    - master
    - develop

Build GCloud Additional Image:
  extends: .Build Additional Image
  variables:
    ADDITION: gcloud

Build Docker Additional Image:
  extends: .Build Additional Image
  variables:
    ADDITION: docker

Build AWS Additional Image:
  extends: .Build Additional Image
  variables:
    ADDITION: aws

Build AWS Docker Additional Image:
  extends: .Build Additional Image
  variables:
    ADDITION: aws-docker
